#!/usr/bin/env python
import collections
import subprocess
import sys

ExecutionResult = collections.namedtuple(
    'ExecutionResult',
    'status, stdout, stderr'
)


def _execute(cmd):
    process = subprocess.Popen(
        cmd,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE
    )
    stdout, stderr = process.communicate()
    status = process.poll()
    return ExecutionResult(status, stdout, stderr)

changes = _execute(['git', 'diff', '--staged'])
if 'print ' in changes.stdout:
    print "print detected in changes. Use Logging instead"
    sys.exit(1)
else:
    sys.exit(0)

test_output = _execute(['nose2'])
print test_output

